language: node_js
branches:
  only:
    - master
    - test/cbt
    - test/capture
matrix:
  include:
    # Unit tests on Node Stable
    - node_js: 8
      env:
        - CBT_USERNAME=lynnjepsen@google.com
        - CBT_AUTHKEY=u868c28eafe8a854
      script: npm run build && npm run pretest && npm run test:ci && npm run posttest
      after_success:
        - codecov
    # Image diff tests on Node Stable
    - node_js: 8
      env:
        - CBT_USERNAME=lynnjepsen@google.com
        - CBT_AUTHKEY=u868c28eafe8a854
      script: npm stop && ./test/screenshot/start.sh && sleep 10s && npm run test:image-diff && npm stop
    # Closure compiler type checking. Note that TravisCI has Java 7 enabled by default which should
    # work for using closure.
    - node_js: node
      # Make more clear that this job is for running closure tests
      env:
        - CLOSURE=1
      script: npm run test:closure
